baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Butterfly Realm'
theme = 'ananke'
relativeURLs = true

[params]
  description = "A comprehensive guide to the beautiful world of butterflies."
  custom_css = ["css/blue.css"]
  background_color_class = "bg-blue"
  body_classes = "avenir bg-washed-blue"
